// Code generated by protoc-gen-go. DO NOT EDIT.
// source: stee_riskmgr.proto

package mobile

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type STEERiskMgrGetReportConfigResponse_STEEConfigAction int32

const (
	STEERiskMgrGetReportConfigResponse_ATONCE STEERiskMgrGetReportConfigResponse_STEEConfigAction = 0
	STEERiskMgrGetReportConfigResponse_GIVEUP STEERiskMgrGetReportConfigResponse_STEEConfigAction = 1
)

var STEERiskMgrGetReportConfigResponse_STEEConfigAction_name = map[int32]string{
	0: "ATONCE",
	1: "GIVEUP",
}

var STEERiskMgrGetReportConfigResponse_STEEConfigAction_value = map[string]int32{
	"ATONCE": 0,
	"GIVEUP": 1,
}

func (x STEERiskMgrGetReportConfigResponse_STEEConfigAction) Enum() *STEERiskMgrGetReportConfigResponse_STEEConfigAction {
	p := new(STEERiskMgrGetReportConfigResponse_STEEConfigAction)
	*p = x
	return p
}

func (x STEERiskMgrGetReportConfigResponse_STEEConfigAction) String() string {
	return proto.EnumName(STEERiskMgrGetReportConfigResponse_STEEConfigAction_name, int32(x))
}

func (x *STEERiskMgrGetReportConfigResponse_STEEConfigAction) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(STEERiskMgrGetReportConfigResponse_STEEConfigAction_value, data, "STEERiskMgrGetReportConfigResponse_STEEConfigAction")
	if err != nil {
		return err
	}
	*x = STEERiskMgrGetReportConfigResponse_STEEConfigAction(value)
	return nil
}

func (STEERiskMgrGetReportConfigResponse_STEEConfigAction) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0343e6543653744e, []int{1, 0}
}

// 数据采集配置
type STEERiskMgrGetReportConfigRequest struct {
	Tag                  *string  `protobuf:"bytes,1,req,name=tag" json:"tag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *STEERiskMgrGetReportConfigRequest) Reset()         { *m = STEERiskMgrGetReportConfigRequest{} }
func (m *STEERiskMgrGetReportConfigRequest) String() string { return proto.CompactTextString(m) }
func (*STEERiskMgrGetReportConfigRequest) ProtoMessage()    {}
func (*STEERiskMgrGetReportConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0343e6543653744e, []int{0}
}

func (m *STEERiskMgrGetReportConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_STEERiskMgrGetReportConfigRequest.Unmarshal(m, b)
}
func (m *STEERiskMgrGetReportConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_STEERiskMgrGetReportConfigRequest.Marshal(b, m, deterministic)
}
func (m *STEERiskMgrGetReportConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_STEERiskMgrGetReportConfigRequest.Merge(m, src)
}
func (m *STEERiskMgrGetReportConfigRequest) XXX_Size() int {
	return xxx_messageInfo_STEERiskMgrGetReportConfigRequest.Size(m)
}
func (m *STEERiskMgrGetReportConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_STEERiskMgrGetReportConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_STEERiskMgrGetReportConfigRequest proto.InternalMessageInfo

func (m *STEERiskMgrGetReportConfigRequest) GetTag() string {
	if m != nil && m.Tag != nil {
		return *m.Tag
	}
	return ""
}

type STEERiskMgrGetReportConfigResponse struct {
	Action               *STEERiskMgrGetReportConfigResponse_STEEConfigAction `protobuf:"varint,1,req,name=action,enum=com.dingxiang.mobile.STEERiskMgrGetReportConfigResponse_STEEConfigAction" json:"action,omitempty"`
	Filters              []string                                             `protobuf:"bytes,2,rep,name=filters" json:"filters,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                             `json:"-"`
	XXX_unrecognized     []byte                                               `json:"-"`
	XXX_sizecache        int32                                                `json:"-"`
}

func (m *STEERiskMgrGetReportConfigResponse) Reset()         { *m = STEERiskMgrGetReportConfigResponse{} }
func (m *STEERiskMgrGetReportConfigResponse) String() string { return proto.CompactTextString(m) }
func (*STEERiskMgrGetReportConfigResponse) ProtoMessage()    {}
func (*STEERiskMgrGetReportConfigResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0343e6543653744e, []int{1}
}

func (m *STEERiskMgrGetReportConfigResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_STEERiskMgrGetReportConfigResponse.Unmarshal(m, b)
}
func (m *STEERiskMgrGetReportConfigResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_STEERiskMgrGetReportConfigResponse.Marshal(b, m, deterministic)
}
func (m *STEERiskMgrGetReportConfigResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_STEERiskMgrGetReportConfigResponse.Merge(m, src)
}
func (m *STEERiskMgrGetReportConfigResponse) XXX_Size() int {
	return xxx_messageInfo_STEERiskMgrGetReportConfigResponse.Size(m)
}
func (m *STEERiskMgrGetReportConfigResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_STEERiskMgrGetReportConfigResponse.DiscardUnknown(m)
}

var xxx_messageInfo_STEERiskMgrGetReportConfigResponse proto.InternalMessageInfo

func (m *STEERiskMgrGetReportConfigResponse) GetAction() STEERiskMgrGetReportConfigResponse_STEEConfigAction {
	if m != nil && m.Action != nil {
		return *m.Action
	}
	return STEERiskMgrGetReportConfigResponse_ATONCE
}

func (m *STEERiskMgrGetReportConfigResponse) GetFilters() []string {
	if m != nil {
		return m.Filters
	}
	return nil
}

type STEERiskMgrReportDataRequest struct {
	Infos                []*STEERiskMgrReportDataRequest_STEEInfoItem `protobuf:"bytes,1,rep,name=infos" json:"infos,omitempty"`
	UsrInfos             []*STEERiskMgrReportDataRequest_STEEInfoItem `protobuf:"bytes,2,rep,name=usr_infos,json=usrInfos" json:"usr_infos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                     `json:"-"`
	XXX_unrecognized     []byte                                       `json:"-"`
	XXX_sizecache        int32                                        `json:"-"`
}

func (m *STEERiskMgrReportDataRequest) Reset()         { *m = STEERiskMgrReportDataRequest{} }
func (m *STEERiskMgrReportDataRequest) String() string { return proto.CompactTextString(m) }
func (*STEERiskMgrReportDataRequest) ProtoMessage()    {}
func (*STEERiskMgrReportDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0343e6543653744e, []int{2}
}

func (m *STEERiskMgrReportDataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_STEERiskMgrReportDataRequest.Unmarshal(m, b)
}
func (m *STEERiskMgrReportDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_STEERiskMgrReportDataRequest.Marshal(b, m, deterministic)
}
func (m *STEERiskMgrReportDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_STEERiskMgrReportDataRequest.Merge(m, src)
}
func (m *STEERiskMgrReportDataRequest) XXX_Size() int {
	return xxx_messageInfo_STEERiskMgrReportDataRequest.Size(m)
}
func (m *STEERiskMgrReportDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_STEERiskMgrReportDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_STEERiskMgrReportDataRequest proto.InternalMessageInfo

func (m *STEERiskMgrReportDataRequest) GetInfos() []*STEERiskMgrReportDataRequest_STEEInfoItem {
	if m != nil {
		return m.Infos
	}
	return nil
}

func (m *STEERiskMgrReportDataRequest) GetUsrInfos() []*STEERiskMgrReportDataRequest_STEEInfoItem {
	if m != nil {
		return m.UsrInfos
	}
	return nil
}

// 数据采集上传
type STEERiskMgrReportDataRequest_STEEInfoItem struct {
	Name                 *string  `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Value                *string  `protobuf:"bytes,2,req,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *STEERiskMgrReportDataRequest_STEEInfoItem) Reset() {
	*m = STEERiskMgrReportDataRequest_STEEInfoItem{}
}
func (m *STEERiskMgrReportDataRequest_STEEInfoItem) String() string { return proto.CompactTextString(m) }
func (*STEERiskMgrReportDataRequest_STEEInfoItem) ProtoMessage()    {}
func (*STEERiskMgrReportDataRequest_STEEInfoItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_0343e6543653744e, []int{2, 0}
}

func (m *STEERiskMgrReportDataRequest_STEEInfoItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_STEERiskMgrReportDataRequest_STEEInfoItem.Unmarshal(m, b)
}
func (m *STEERiskMgrReportDataRequest_STEEInfoItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_STEERiskMgrReportDataRequest_STEEInfoItem.Marshal(b, m, deterministic)
}
func (m *STEERiskMgrReportDataRequest_STEEInfoItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_STEERiskMgrReportDataRequest_STEEInfoItem.Merge(m, src)
}
func (m *STEERiskMgrReportDataRequest_STEEInfoItem) XXX_Size() int {
	return xxx_messageInfo_STEERiskMgrReportDataRequest_STEEInfoItem.Size(m)
}
func (m *STEERiskMgrReportDataRequest_STEEInfoItem) XXX_DiscardUnknown() {
	xxx_messageInfo_STEERiskMgrReportDataRequest_STEEInfoItem.DiscardUnknown(m)
}

var xxx_messageInfo_STEERiskMgrReportDataRequest_STEEInfoItem proto.InternalMessageInfo

func (m *STEERiskMgrReportDataRequest_STEEInfoItem) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *STEERiskMgrReportDataRequest_STEEInfoItem) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

type STEERiskMgrReportDataResponse struct {
	Constid              *string  `protobuf:"bytes,1,req,name=constid" json:"constid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *STEERiskMgrReportDataResponse) Reset()         { *m = STEERiskMgrReportDataResponse{} }
func (m *STEERiskMgrReportDataResponse) String() string { return proto.CompactTextString(m) }
func (*STEERiskMgrReportDataResponse) ProtoMessage()    {}
func (*STEERiskMgrReportDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0343e6543653744e, []int{3}
}

func (m *STEERiskMgrReportDataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_STEERiskMgrReportDataResponse.Unmarshal(m, b)
}
func (m *STEERiskMgrReportDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_STEERiskMgrReportDataResponse.Marshal(b, m, deterministic)
}
func (m *STEERiskMgrReportDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_STEERiskMgrReportDataResponse.Merge(m, src)
}
func (m *STEERiskMgrReportDataResponse) XXX_Size() int {
	return xxx_messageInfo_STEERiskMgrReportDataResponse.Size(m)
}
func (m *STEERiskMgrReportDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_STEERiskMgrReportDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_STEERiskMgrReportDataResponse proto.InternalMessageInfo

func (m *STEERiskMgrReportDataResponse) GetConstid() string {
	if m != nil && m.Constid != nil {
		return *m.Constid
	}
	return ""
}

func init() {
	proto.RegisterEnum("com.dingxiang.mobile.STEERiskMgrGetReportConfigResponse_STEEConfigAction", STEERiskMgrGetReportConfigResponse_STEEConfigAction_name, STEERiskMgrGetReportConfigResponse_STEEConfigAction_value)
	proto.RegisterType((*STEERiskMgrGetReportConfigRequest)(nil), "com.dingxiang.mobile.STEERiskMgrGetReportConfigRequest")
	proto.RegisterType((*STEERiskMgrGetReportConfigResponse)(nil), "com.dingxiang.mobile.STEERiskMgrGetReportConfigResponse")
	proto.RegisterType((*STEERiskMgrReportDataRequest)(nil), "com.dingxiang.mobile.STEERiskMgrReportDataRequest")
	proto.RegisterType((*STEERiskMgrReportDataRequest_STEEInfoItem)(nil), "com.dingxiang.mobile.STEERiskMgrReportDataRequest.STEEInfoItem")
	proto.RegisterType((*STEERiskMgrReportDataResponse)(nil), "com.dingxiang.mobile.STEERiskMgrReportDataResponse")
}

func init() { proto.RegisterFile("stee_riskmgr.proto", fileDescriptor_0343e6543653744e) }

var fileDescriptor_0343e6543653744e = []byte{
	// 329 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x91, 0xcf, 0x4a, 0xc3, 0x40,
	0x10, 0xc6, 0x4d, 0x62, 0x5b, 0x3b, 0x8a, 0x84, 0xa5, 0x87, 0x20, 0x0a, 0x35, 0xa7, 0xe2, 0x21,
	0x87, 0x82, 0xa0, 0x27, 0xa9, 0x35, 0xd4, 0x1c, 0xfc, 0xc3, 0xda, 0x7a, 0x12, 0xca, 0xda, 0x6e,
	0xc2, 0xd2, 0x66, 0xb7, 0xee, 0x6c, 0xc4, 0x97, 0xf0, 0xd1, 0x7c, 0x27, 0xe9, 0x26, 0x85, 0xe2,
	0xbf, 0x5e, 0xbc, 0xcd, 0x37, 0xb3, 0xdf, 0x6f, 0xbf, 0xdd, 0x01, 0x82, 0x86, 0xf3, 0xb1, 0x16,
	0x38, 0xcb, 0x33, 0x1d, 0x2d, 0xb4, 0x32, 0x8a, 0xb4, 0x26, 0x2a, 0x8f, 0xa6, 0x42, 0x66, 0x6f,
	0x82, 0xc9, 0x2c, 0xca, 0xd5, 0xb3, 0x98, 0xf3, 0xf0, 0x14, 0x8e, 0x1f, 0x86, 0x71, 0x4c, 0x05,
	0xce, 0x6e, 0x32, 0x3d, 0xe0, 0x86, 0xf2, 0x85, 0xd2, 0xa6, 0xaf, 0x64, 0x2a, 0x32, 0xca, 0x5f,
	0x0a, 0x8e, 0x86, 0xf8, 0xe0, 0x19, 0x96, 0x05, 0x4e, 0xdb, 0xed, 0x34, 0xe9, 0xb2, 0x0c, 0x3f,
	0x1c, 0x08, 0xff, 0xf2, 0xe1, 0x42, 0x49, 0xe4, 0x84, 0x41, 0x9d, 0x4d, 0x8c, 0x50, 0xd2, 0x7a,
	0xf7, 0xbb, 0x49, 0xf4, 0x53, 0x88, 0x68, 0x33, 0xc9, 0x1e, 0x29, 0x5b, 0x3d, 0x0b, 0xa4, 0x15,
	0x98, 0x04, 0xd0, 0x48, 0xc5, 0xdc, 0x70, 0x8d, 0x81, 0xdb, 0xf6, 0x3a, 0x4d, 0xba, 0x92, 0xe1,
	0x09, 0xf8, 0x5f, 0x5d, 0x04, 0xa0, 0xde, 0x1b, 0xde, 0xdd, 0xf6, 0x63, 0x7f, 0x6b, 0x59, 0x0f,
	0x92, 0xc7, 0x78, 0x74, 0xef, 0x3b, 0xe1, 0xbb, 0x0b, 0x87, 0x6b, 0x29, 0xca, 0x08, 0x57, 0xcc,
	0xb0, 0xd5, 0x17, 0x8c, 0xa0, 0x26, 0x64, 0xaa, 0x30, 0x70, 0xda, 0x5e, 0x67, 0xb7, 0x7b, 0xb1,
	0xf1, 0x21, 0xdf, 0x10, 0x76, 0x98, 0xc8, 0x54, 0x25, 0x86, 0xe7, 0xb4, 0xa4, 0x91, 0x27, 0x68,
	0x16, 0xa8, 0xc7, 0x25, 0xda, 0xfd, 0x1f, 0xf4, 0x4e, 0x81, 0x7a, 0x29, 0xf0, 0xe0, 0x0c, 0xf6,
	0xd6, 0x27, 0x84, 0xc0, 0xb6, 0x64, 0x39, 0xaf, 0x16, 0x69, 0x6b, 0xd2, 0x82, 0xda, 0x2b, 0x9b,
	0x17, 0x3c, 0x70, 0x6d, 0xb3, 0x14, 0xe1, 0x39, 0x1c, 0xfd, 0x72, 0x61, 0xb5, 0xd9, 0x00, 0x1a,
	0x13, 0x25, 0xd1, 0x88, 0x69, 0x45, 0x5b, 0xc9, 0x4b, 0xf7, 0xda, 0xfb, 0x0c, 0x00, 0x00, 0xff,
	0xff, 0xbf, 0xd9, 0xb8, 0x9f, 0x80, 0x02, 0x00, 0x00,
}
