linters:
  enable-all: true
  disable:
    - depguard
    - dupl
    - gochecknoglobals
    - gochecknoinits
    - goconst
    - gocyclo
    - gosec
    - nakedret
    - prealloc
    - scopelint
    - lll
    - typecheck
  fast: true
